[build]
  command = "ng build --configuration production"
  publish = "dist/book-bus-tickets/browser"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
