[build]
  command = "ng build --configuration production"
  publish = "dist/book-bus-tickets/browser"

[[redirects]]
  from = "/api/*"
  to = "https://projectapi.gerasim.in/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
